In [1]:
import torch
import torch.nn as nn

In [77]:
7 // 2

3

In [65]:
m = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=1, bias=False)

In [66]:
m.weight.shape

torch.Size([1, 1, 3, 3])

In [74]:
# with torch.no_grad:
m.weight = nn.Parameter(torch.rand(1, 1, 3, 3), requires_grad=True)

In [55]:
m.weight = nn.Parameter(torch.rand(1,1,3,3))

In [56]:
m.weight

Parameter containing:
tensor([[[[0.9425, 0.3161, 0.2618],
          [0.4307, 0.0948, 0.5175],
          [0.5267, 0.3133, 0.5563]]]], requires_grad=True)

In [49]:
torch.sum(m.weight)

tensor(-0.8992, grad_fn=<SumBackward0>)

In [10]:
import numpy as np
import cv2

In [14]:
im = cv2.imread("/home/re6091054/FF++/c40/train/Real/001/0.png")[:,:,::-1]

In [39]:
tensor_im = torch.from_numpy(im.astype(float)).float()

In [42]:
# (betch, n_channels, height, width)
tensor_im.unsqueeze(0).permute(0, 3, 1, 2).shape

torch.Size([1, 3, 259, 226])

In [43]:
m(tensor_im.unsqueeze(0).permute(0, 3, 1, 2)).shape

torch.Size([1, 3, 259, 226])

In [78]:
from scipy.fftpack import dct, idct

In [79]:
import numpy as np
from numpy import array, zeros

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [82]:
dct(dct(zeros((8,8)), norm = 'ortho').transpose(), norm = 'ortho')

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])